- name: add user {{ ssh_user }}
  user: name={{ ssh_user }} groups="sudo" shell="/bin/bash"
  sudo: yes
  when: ssh_user is defined

- name: add authorized key {{ ssh_pub_key }} for user {{ ssh_user }}
  authorized_key: user={{ ssh_user }} key="{{ ssh_pub_key }}" manage_dir=no
  sudo: yes
  when: ssh_user is defined and ssh_pub_key is defined

- name: add user {{ ssh_user }} to sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^{{ ssh_user }}' line='{{ ssh_user }} ALL=(ALL) NOPASSWD: ALL'"
  sudo: yes

- name: apt update
  apt: update_cache=yes
  sudo: yes

- name: install system base packages
  apt: name={{item}}
  with_items:
    - upstart
    - git
    - python-pip
  sudo: yes
