language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3

script: python setup.py test

install: pip install -r requirements.txt && pip install -r requirements-test.txt

notifications:
  email: false