process_html:
    path:       /process_html
    methods:    POST
    controller: uncss.api.clean.ProcessHtml

clean_css:
    path:       /clean_css
    methods:    POST
    controller: uncss.api.clean.CleanCss

get_css:
    path:       /get_css/{css_key}
    methods:    GET
    controller: uncss.api.clean.GetCss