process_html:
    path:       /process_html/{url}
    methods:     GET
    controller: uncss.api.clean.ProcessHtml

clean_css:
    path:       /clean_css/{html_key}/{css_source_url}
    methods:     GET
    controller: uncss.api.clean.CleanCss

get_css:
    path:       /get_css/{css_key}
    methods:     GET
    controller: uncss.api.clean.GetCss